name: bio_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.15.3=hb03c661_0
  - bedtools=2.31.1=h13024bc_3
  - blast=2.16.0=h66d330f_5
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bwa=0.7.19=h577a1d6_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - circos=0.69.9=hdfd78af_0
  - contourpy=1.3.3=py313h7037e92_3
  - curl=8.18.0=h4e3cde8_0
  - cycler=0.12.1=pyhcf101f3_2
  - entrez-direct=22.4=he881be0_0
  - expat=2.7.3=hecca717_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - giflib=5.2.2=hd590300_0
  - glimmerhmm=3.0.4=pl5321h503566f_10
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=12.3.0=h6083320_0
  - icu=78.2=h33c6efd_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - k8=1.2=he8db53b_6
  - kernel-headers_linux-64=6.12.0=he073ed8_5
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgd=2.3.3=h5fbf134_12
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.86.3=h6548e54_0
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.54=h421ea60_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.7.1=h9d88235_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-base=3.10.8=py313h683a580_0
  - minimap2=2.30=h577a1d6_0
  - mpi=1.0=openmpi
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncbi-vdb=3.3.0=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.1=py313hf6604e3_0
  - openjdk=25.0.1=h5755bd7_0
  - openjpeg=2.5.4=h55fea9a_0
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.47=haa7fec5_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-b-cow=0.007=pl5321hb9d3cd8_1
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-clone=0.46=pl5321hb9d3cd8_1
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.214=pl5321hda65f42_0
  - perl-compress-raw-zlib=2.214=pl5321h4dac143_0
  - perl-config-general=2.67=pl5321hdfd78af_0
  - perl-digest-perl-md5=1.9=pl5321hdfd78af_2
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-config=0.008=pl5321ha770c72_0
  - perl-extutils-helpers=0.026=pl5321ha770c72_0
  - perl-extutils-installpaths=0.012=pl5321ha770c72_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-extutils-pl2bat=0.005=pl5321ha770c72_0
  - perl-font-ttf=1.06=pl5321hdfd78af_1
  - perl-gd=2.84=pl5321hc25ab4d_0
  - perl-inc-latest=0.500=pl5321ha770c72_0
  - perl-io-compress=2.214=pl5321h503566f_0
  - perl-io-string=1.08=pl5321hdfd78af_4
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.04=pl5321h9948957_0
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-math-bezier=0.01=pl5321hdfd78af_2
  - perl-math-round=0.07=pl5321ha770c72_0
  - perl-math-vecstat=0.08=pl5321hdfd78af_2
  - perl-module-build=0.4234=pl5321ha770c72_1
  - perl-module-build-tiny=0.039=pl5321h166bdaf_0
  - perl-module-implementation=0.09=pl5321ha770c72_1
  - perl-module-runtime=0.016=pl5321ha770c72_1
  - perl-number-format=1.76=pl5321hd8ed1ab_0
  - perl-params-validate=1.31=pl5321h7b50bb2_5
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-readonly=2.05=pl5321ha770c72_0
  - perl-regexp-common=2017060201=pl5321hd8ed1ab_0
  - perl-scalar-list-utils=1.70=pl5321hb03c661_0
  - perl-set-intspan=1.19=pl5321hdfd78af_2
  - perl-statistics-basic=1.6611=pl5321hdfd78af_3
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-svg=2.87=pl5321hd8ed1ab_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-test-nowarnings=1.06=pl5321ha770c72_0
  - perl-text-format=0.63=pl5321hdfd78af_0
  - perl-time-hires=1.9764=pl5321h7b50bb2_6
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-xml-parser=2.44_01=pl5321hf2e2c51_1004
  - pillow=12.1.0=py313h80991f8_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.3.1=pyhcf101f3_0
  - python=3.13.11=hc97d973_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.13=8_cp313
  - qhull=2020.2=h434a139_5
  - quast=5.3.0=py313pl5321h5ca1c30_2
  - readline=8.3=h853b02a_0
  - rpsbproc=0.5.0=hd6d6fdc_3
  - setuptools=80.9.0=pyhff2d567_0
  - simplejson=3.20.2=py313h07c4f96_1
  - six=1.17.0=pyhe01879c_1
  - spades=4.2.0=h8d6e82b_2
  - sysroot_linux-64=2.39=hc4b9eeb_5
  - tk=8.6.13=noxft_ha0e22de_103
  - tzdata=2025c=hc9c84f9_1
  - wget=1.21.4=hda4d442_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/faithigo/anaconda3/envs/bio_env
